import { Roboto, Roboto_Mono, Cormorant_Infant } from "next/font/google";
import "./globals.css";

const sans = Roboto({
    variable: "--font-roboto-sans",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const mono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const serif = Cormorant_Infant({
    variable: "--font-cormorant",
    weight: "400",
    subsets: ["latin"],
});

export const metadata = {
    title: "Etherealm",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`flex items-center justify-center min-h-screen ${sans.variable} ${mono.variable} ${serif.variable} antialiased bg-background text-text`}
            >
                {children}
            </body>
        </html>
    );
}
